title: "Aska Intelligence"
email: contact@aska.systems
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/Aska_icon_circle.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
default_lang: en
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  aska_studio:
    name: Aska Studio
    display_name: Aska Studio
    avatar: 'assets/images/sal.png'
    instagram: https://www.instagram.com/aska___studio/
    web: https://www.instagram.com/aska___studio/
    twitter: https://twitter.com/skaIntelligence
    description: ""
  bouquet_diagram:
    name: Bouquet Diagram
    display_name: Bouquet Diagram
    avatar: 'assets/images/john.png'
    instagram: https://www.instagram.com/bouquet_diagram/
    web: https://www.instagram.com/bouquet_diagram/
    twitter: https://twitter.com/skaIntelligence
    description: ""

# Social
social:
  instagram: https://www.instagram.com/bouquet_diagram/
  facebook: https://www.facebook.com/Aska.systems
  # twitter: https://twitter.com/skaIntelligence

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives